### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by tingsu** [linuxtage/glt-companion#4]
version code: 10
version name: 1.2.0
device sdk version: android-18

java.lang.RuntimeException: Unable to start activity ComponentInfo{at.linuxtage.companion/at.linuxtage.companion.JacocoInstrument.InstrumentedActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
 	at android.support.v7.app.ActionBarActivityDelegateBase.setSupportActionBar(ActionBarActivityDelegateBase.java:165)
 	at android.support.v7.app.ActionBarActivity.setSupportActionBar(ActionBarActivity.java:92)
 	at at.linuxtage.companion.activities.MainActivity.onCreate(MainActivity.java:195)
 	at android.app.Activity.performCreate(Activity.java:5133)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)

**Comment by flowolf** [comment]
thanks for the report. we will look into it before the next event.

**Comment by flowolf** [comment]
please reproduce this error on the current version 1.4.5 ([APK](https://linuxtage.at/betaapp))
otherwise we can consider it fixed - the version you reported was already outdated back in August 2017 (current was 1.4.4).
