### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by tingsu** [linuxtage/glt-companion#5]
version code: 700138
version name: 1.3.8
target sdk version: android-18

java.lang.RuntimeException: Unable to start activity ComponentInfo{at.linuxtage.companion/at.linuxtage.companion.activities.EventDetailsActivity}: java.lang.NumberFormatException: Invalid long: "null"
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.NumberFormatException: Invalid long: "null"
 	at java.lang.Long.invalidLong(Long.java:125)
 	at java.lang.Long.parseLong(Long.java:342)
 	at java.lang.Long.parseLong(Long.java:319)
 	at at.linuxtage.companion.activities.EventDetailsActivity.onCreateLoader(EventDetailsActivity.java:132)
 	at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:539)
 	at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:548)
 	at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:602)
 	at at.linuxtage.companion.activities.EventDetailsActivity.onCreate(EventDetailsActivity.java:58)
 	at android.app.Activity.performCreate(Activity.java:5133)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)

**Comment by flowolf** [comment]
thanks for the report. we will look into it before the next event.

**Comment by meisterluk** [comment]
@tingsu Can you give a hint, what you where about to do / trying to do when the Exception occured?

**Comment by flowolf** [comment]
please reproduce this error on the current version 1.4.5 ([APK](https://linuxtage.at/betaapp))
otherwise we can consider it fixed - the version you reported was already outdated back in August 2017 (current was 1.4.4).
