### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by tingsu** [linuxtage/glt-companion#6]
version code: 700138
version name: 1.3.8
target sdk version: android-18

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=www.ansible.com }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
 	at android.app.Activity.startActivityForResult(Activity.java:3390)
 	at android.app.Activity.startActivityForResult(Activity.java:3351)
 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
 	at android.app.Activity.startActivity(Activity.java:3587)
 	at android.app.Activity.startActivity(Activity.java:3555)
 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:290)
 	at at.linuxtage.companion.fragments.EventDetailsFragment$LinkClickListener.onClick(EventDetailsFragment.java:482)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View$PerformClick.run(View.java:17721)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by flowolf** [comment]
thanks for the report. we will look into it before the next event.

**Comment by flowolf** [comment]
please reproduce this error on the current version 1.4.5 ([APK](https://linuxtage.at/betaapp))
otherwise we can consider it fixed - the version you reported was already outdated back in August 2017 (current was 1.4.4).
